export const SET_TOKEN = 'SET_TOKEN'
export const SET_MENU_LIST = 'SET_MENU_LIST'
export const SET_PERMISSION_LIST = 'SET_PERMISSION_LIST'
export const SET_ROUTE_STATUS = 'SET_ROUTE_STATUS'
export const SET_TAB = 'SET_TAB'
export const RESET_TAB = 'RESET_TAB'
export const RESET_MENU_STATE = 'RESET_MENU_STATE'
export const SET_ROLE = 'SET_ROLE'
export const SET_POST = 'SET_POST'
export const SET_DEPARTMENT = 'SET_DEPARTMENT'
export const SET_EMPLOYEE = 'SET_EMPLOYEE'
export const RESET_ALL = 'RESET_ALL'
export const SET_LEVEL2_MENU = 'SET_LEVEL2_MENU'
export const SET_MENU_DATA = 'SET_MENU_DATA'

